---
- name: Create codis server work directory
  file: path={{ codis_server_workdir }}-{{ codis_server_port }} state=directory owner=codis group=codis

- name: Copy codis-server binary
  copy: src={{ codis_dir }}/bin/codis-server dest={{ codis_install_dir }}/bin/codis-server mode=766

- name: Copy codis-server configuration
  template: src=redis.conf dest={{ codis_install_dir }}/config/redis-{{ codis_server_port }}.conf

- name: Copy codis-server admin script
  template: src=codis-server-admin.sh dest={{ codis_install_dir }}/admin/codis-server-admin-{{ codis_server_port }}.sh mode=766

- name: Restart codis-server service
  command: "{{ codis_install_dir }}/admin/codis-server-admin-{{ codis_server_port }}.sh restart"
